# Generated by Django 3.2 on 2021-06-05 20:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20210605_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtaa',
            name='image',
        ),
        migrations.AddField(
            model_name='mtaa',
            name='cloudinary_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
