# Generated by Django 3.2 on 2021-06-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20210605_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Mtaa',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='essential',
            old_name='Mtaa',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Mtaa',
            new_name='location',
        ),
    ]
