# Generated by Django 3.2 on 2021-06-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20210607_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.RemoveField(
            model_name='essential',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
